name: ServerSpecs
version: '1.0'
main: me.buggyal.serverspecs.ServerSpecs
api-version: '1.20'
authors: [BuggyAl]
description: Attempts to scan a Minecraft server for the hardware stats. Useful for server hosts like Minehut that don't specifically state the server hardware.
